#!/usr/bin/env python3

"""
author: Thierry Haddad
description: Parses sequon windows (15 aminoa acids) from the ASCII PSSM
             generated by psiblast. Does this for every sequon for every
             protein in the dataset.
"""

### NOTE: Currently only testing some sequons for parsing correctness.

data_f = "/mnt/scratch/hadda003/negative_set/pos_neg_table.txt"
with open(data_f, "r") as f:
    data = f.readlines()
pssm_f = "subset_100_individual_pssms.txt.1"
with open(pssm_f, "r") as f:
    pssm = f.readlines()

header = pssm[2].split()[:20]
print(header)
sequon = int(data[0].split()[2])
window = pssm[(sequon)-4:(sequon)+11]
for line in window:
    print(line.split()[2:22])

